### PR TITLE
Single scrollbar

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/src-d/code-annotation/issues/146

before
image

After
image

image

### CODE REVIEW

**Comment by bzz** [comment]
@smacker so both, FF and Chrome are tested and have the small behaviour of a single.scroll-bar for a file pair now?

**Comment by smacker** [comment]
Yes. Both have same behavior of single scroll bar. That is what issue & PR are about, no?

**Review by dpordomingo — COMMENTED** [review]
As it can be seen in the screenshot, horizontal scrollbars are cropped in Chrome.
But what might be worst is that to do horizontal scroll, the user needs to scroll to the bottom of the page because that's the new position of the horizontal scrollbars.
Is that behavior expected for the users?

**Comment by dpordomingo** [comment]
Please, @smacker add screenshots to the PR descriptions when the changes have an impact on the UI.
I already did it to this PR because I needed them to provide my feedback, but it would be useful if it is done by the one who creates the PR :wink:

**Comment by smacker** [comment]
@dpordomingo hm. On mac os scrollbars are ok. But I'll try to check and fix (will need test from somebody on linux though later anyway). Thanks!

**Comment by smacker** [comment]
@dpordomingo there are no visual changes on mac os compare to master.

**Comment by dpordomingo** [comment]
The thing that concerns me more is the necessity of scroll to the bottom to do h-scrolling; I think it should be approved by @ricardobaeta and/or our users to ensure it fits its expectations

**Comment by bzz** [comment]
Thank you for rising this, @dpordomingo !

> the necessity of scroll to the bottom to do h-scrolling

I'm sure @vmarkovtsev as the author of #146 will be happy to provide input on this here ASAP

**Review by bzz — APPROVED** [review]
LGTM

as soon as we know if https://github.com/src-d/code-annotation/pull/147#issuecomment-367268179 is acceptable for users or find a better solution

**Comment by smacker** [comment]
> The thing that concerns me more is the necessity of scroll to the bottom to do h-scrolling

makes sense. I don't use a mouse, so I didn't even think about it. Please give me a bit of time. I'll try to fix cropped scrollbar on non mac os and this issue.

**Review by dpordomingo — APPROVED** [review]
LGTM, 
@smacker you can merge

**Review by carlosms — APPROVED** [review]

**Comment by smacker** [comment]
For the history: on Mac OS in FF it works but the feeling of the scroll is broken. On Linux it works well in both browsers.
We decided it's good enough for now. We will ask Mac OS users to switch to Chrome.

**Pull request merged**
