### PR TITLE
Implement features endpoint

### PR DESCRIPTION
**Pull request by smacker**
Fixes https://github.com/src-d/code-annotation/issues/44

### CODE REVIEW

**Comment by bzz** [comment]
\cc @carlosms for review

**Comment by carlosms** [comment]
Maybe we should restrict this route only for users with the Requester role. Do you agree?

**Comment by smacker** [comment]
we don't have ACL yet. But we should later, yes.

**Comment by carlosms** [comment]
The roles are already in models.go, and #60 should be merged soon. I'd make this change to save us a new PR in a few hours. Up to you.

Otherwise, looks good.

**Review by carlosms — APPROVED** [review]

**Comment by smacker** [comment]
You won't be able to test it after merge then. I prefer going step by step. In my opinion, the right place to implement it is connection FE to BE. Because the same restriction will be needed on FE side.

**Comment by carlosms** [comment]
I'm ok with any option as long as we don't forget about it. Can you please make a new issue, or add a comment to the relevant issue to make sure we don't forget? Thank you.

**Comment by smacker** [comment]
@carlosms added in https://github.com/src-d/code-annotation/issues/47

**Review by bzz — APPROVED** [review]
LGTM

**Pull request merged**
