### PR TITLE
Connect review page to backend

### PR DESCRIPTION
**Pull request by smacker**
Partly solves https://github.com/src-d/code-annotation/issues/47

Based on https://github.com/src-d/code-annotation/issues/88

### CODE REVIEW

**Review by dpordomingo — APPROVED** [review]

**Comment by smacker** [comment]
I added many new tests and fixed few bug discovered by tests. Now store (except users) is covered close to 100%.

**Review by bzz — APPROVED** [review]
Awesome!

`+2,083 −891` if possible, it would be nice to break such big changes in future to a bit smaller PRs ;)

**Comment by smacker** [comment]
Most of the code are tests. Plus I split experiment & assignments store because experiment is needed for other pages (review for now) too. I could do it in separate PR, that's true.

**Comment by smacker** [comment]
2 approves, I'm merging. But we need to fix this follow up issues:

- https://github.com/src-d/code-annotation/issues/104
- https://github.com/src-d/code-annotation/issues/105
- https://github.com/src-d/code-annotation/issues/106

@bzz please consider adding it to TODO.

**Pull request merged**
