### PR TITLE
use go dep for dependency management

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/src-d/code-annotation/issues/13

### CODE REVIEW

**Review by carlosms — APPROVED** [review]
LGTM

**Review by bzz — APPROVED** [review]
LGTM.

One request, if possible, is there any chance we could merge #29 first and then, in here, also update CONTRIBUTING.md, pointing out that `dep` is used on a backend for dependency management, with a link to something like https://golang.github.io/dep/docs/daily-dep.html ?

Asking as this would help to assimilate the knowledge, necessary to adopt `dep` for other projects.

**Review by mcuadros — CHANGES_REQUESTED** [review]
vendor folder should be upload, otherwise is anti-pattern in go

**Comment by smacker** [comment]
@mcuadros it's not true if we use dep: https://golang.github.io/dep/docs/FAQ.html#best-practices

**Comment by smacker** [comment]
I don't think it's very right decision for this project because go here isn't the main part and in my opinion, it's better to follow the same patterns for all parts of the project. But vendor dir is added.

**Comment by smacker** [comment]
vendor directory is added as Maximo requested. I need this PR to merge another one on top of is so, I'm merging (there are 2 approvals already includes maintainer)

**Comment by mcuadros** [comment]
Why was this PR merged? With a pending request?

**Comment by smacker** [comment]
the request is done.
we need to move faster for code-annotation with merging because we have hard deadlines.

**Comment by smacker** [comment]
oh. and if you are talking about @dpordomingo review, we have an agreement to add everyone of the team in CR. But merge when there is approve of maintainer + 1 more.
If there will be comments later they will go to separate PR.

**Comment by mcuadros** [comment]
Who should confirm if the changes were addressed is the author of the request, since now that the vendor is there the rule `godep`  is not required anymore.

**Comment by smacker** [comment]
godep is still needed for development. Please feel free to add any comments. They will be resolved in additional PRs.

**Comment by mcuadros** [comment]
Also will be nice upload only the package that are you using running first `dep prune` and not all the files

**Comment by smacker** [comment]
Thanks for the suggestion. I created an issue: https://github.com/src-d/code-annotation/issues/39

**Pull request merged**
