### PR TITLE
Add logout button

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/src-d/code-annotation/issues/117

we don't have it on wireframes, so I added it using default bootstrap components and styled dropdown to match overriden theme.

### CODE REVIEW

**Comment by bzz** [comment]
@smacker 🙏 🙏 a screenshot

**Comment by smacker** [comment]
Collapsed:
screen shot 2018-02-15 at 16 11 51

Clicked:
screen shot 2018-02-15 at 16 11 59

This component: https://react-bootstrap.github.io/components/navbar/#navbars-basic

**Comment by ricardobaeta** [comment]
@smacker Please be so kind to use the @brand-info colour for that dropdown icon, or use the .svg.

**Comment by smacker** [comment]
@ricardobaeta done.

**Review by dpordomingo — APPROVED** [review]

**Review by bzz — APPROVED** [review]

**Pull request merged**
