### PR TITLE
Make diff service and increase context

### PR DESCRIPTION
**Pull request by smacker**
Improvements for https://github.com/src-d/code-annotation/issues/112
Moving generation of diff to the handler and increasing context. In real life discussion, guys said most probably 6 lines will be alright. Later with diff generation in the handler, we will be able to increase it further or add configuration in UI or do any other improvements easier if we need.

Also, it allows to preprocess diff on backend for https://github.com/src-d/code-annotation/issues/176
(rendering diff is already expensive, adding preprocessing on FE would degrade user experience further)

### CODE REVIEW

**Review by bzz — APPROVED** [review]
LGTM

👍 for tests and flexibility of diff generation

**Review by dpordomingo — APPROVED** [review]
So now diffs are going to be calculated every time in backend on every request... ok... LGTM

(let's add some cache in the future if performance is impacted)

**Comment by dpordomingo** [comment]
you can merge @smacker

**Comment by smacker** [comment]
I didn't add cache now because diff generation is actually very fast. If we ever meet performance problems it will be easy to add it.

**Pull request merged**
