### PR TITLE
Godep prune

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/src-d/code-annotation/issues/39

1st commit does prune on current vendor dir
2nd commit adds prune to Makefile

### CODE REVIEW

**Comment by carlosms** [comment]
Isn't `dep prune` deprecated? Is there a reason to use `dep prune` instead of setting the [prune settings](https://golang.github.io/dep/docs/Gopkg.toml.html#prune) in Gopkg.toml?

This is what I get in my shell:
```
$ dep prune
Pruning is now performed automatically by dep ensure.
Set prune settings in Gopkg.toml and it it will be applied when running ensure.

This command currently still prunes as it always has, to ease the transition.
However, it will be removed in a future version of dep.

Now is the time to update your Gopkg.toml and remove `dep prune` from any scripts.
```

**Comment by smacker** [comment]
wow. My `dep` doesn't show me any warning. Most probably it's an older version. 
Yeah. Just checked changelog: `Absorb dep prune into dep ensure` 13 days ago. 🤦‍♂️

**Comment by smacker** [comment]
updated to rule in Gopkg.toml. But everybody has to upgrade `dep` to v0.4+

**Review by carlosms — APPROVED** [review]

**Review by dpordomingo — CHANGES_REQUESTED** [review]
I think there are missing things to be deleted and pushed

```bash
rm $GOBIN/dep
go get -u github.com/golang/dep/cmd/dep
git co a4306ec # from PR tip
git status # no changes
make serve
git status # TONS OF DELETIONS in vendor
```

**Comment by smacker** [comment]
@dpordomingo wow! thanks! they changed how it prunes also! I repushed 1st commit with results of v0.4.1

**Review by dpordomingo — APPROVED** [review]
LGTM

I'd squash last two commits begore merging:
54f1988 add dep prune in Makefile
969a4c8 move to prune in Gopkg.toml (requires dep v0.4+)  …

**Review by bzz — APPROVED** [review]
LGTM

**Pull request merged**
