### PR TITLE
Avoid external dependencies

### PR DESCRIPTION
**Pull request by dpordomingo**
Depends on ~~https://github.com/src-d/code-annotation/pull/230~~ https://github.com/src-d/ci/pull/58 https://github.com/src-d/ci/pull/60 https://github.com/src-d/ci/pull/61

Use [src-d/ci:v1](https://github.com/src-d/ci/tree/v1) to avoid external dependencies

### CODE REVIEW

**Comment by dpordomingo** [comment]
Travis fails because https://github.com/src-d/code-annotation/pull/230 has not been yet merged

**Review by carlosms — APPROVED** [review]

**Comment by smacker** [comment]
CI is failing on `make build-app`

**Comment by dpordomingo** [comment]
@smacker ptal https://github.com/src-d/code-annotation/pull/231#comment-376110519

**Comment by smacker** [comment]
aaah. I got it! You can't create this PR on top of #230 because that one for another branch.

**Comment by dpordomingo** [comment]
@smacker #230 was already merged so this PR build already passed; could you ptal again ;)
thanks!

**Review by smacker — APPROVED** [review]
approved, but I still think it's not a good idea to maintain CI fork inside code-annotation project.

**Comment by smacker** [comment]
@bzz maybe you also want to take a look

**Comment by bzz** [comment]
> approved, but I still think it's not a good idea to maintain CI fork inside code-annotation project.

totally see @smacker point and agree


Sorry, I must have missed that, but what was the original reason for having https://github.com/src-d/code-annotation/tree/ci ?

**Comment by dpordomingo** [comment]
@bzz since we cannot use `srcd/ci:v1`, I found the following alternatives:
- (a) [keep relying](https://github.com/src-d/code-annotation/blob/master/Makefile#L27) on `carlosms/ci:add-drone-v1`, dependency outside the company; wich can be deleted without our control and which requires extra overhead for maintenance,
- (b) push this new branch to a new one into `srcd/ci`, for example, `srcd/ci:v1.1-candidate`; I'm not sure if we should push our stuff there, and use it instead of `srcd/ci:v1`
- (c) try to merge the new features into `srcd/ci:v1` &rarr;  https://github.com/src-d/ci/pull/58 https://github.com/src-d/ci/pull/60 waiting since Feb 28th
- (d) create our own `srcd/apps-ci` &rarr; please, no,
- (e) keep this new branch inside this repo

I choose (e) until (c) is unblocked, what would you purpose?

**Comment by dpordomingo** [comment]
internal branch (e) is no longer needed since https://github.com/src-d/ci/pull/58 https://github.com/src-d/ci/pull/60 https://github.com/src-d/ci/pull/61 PRs were just merged

**Pull request merged**
