### PR TITLE
Fix .travis.yml testing configuration

### PR DESCRIPTION
**Pull request by smacker**
Fixes https://github.com/src-d/code-annotation/issues/26

### CODE REVIEW

**Review by dpordomingo — APPROVED** [review]

**Review by dpordomingo — COMMENTED** [review]
Why not adding `CI=1` to the `make test` so we'll run the tests the same way it is done in the CI?
Or is there any special benefit on running the tests in no-CI mode?

**Comment by smacker** [comment]
in CI it uses `CI=1` anyway. Locally without `CI=1` it has the benefit of watching. I love this feature, it helps to iterate on tests much faster.

**Comment by dpordomingo** [comment]
yes, the watch option is very useful while we're developing... so it LGTM

**Review by carlosms — APPROVED** [review]

**Review by bzz — APPROVED** [review]
LGTM

**Pull request merged**
