### PR TITLE
Create components based on visual design

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/src-d/code-annotation/issues/64

This PR beings visual design from https://github.com/src-d/code-annotation/pull/53 but code is separated to reusable components.
It doesn't break other pages.

screen shot 2018-02-07 at 12 49 28

### CODE REVIEW

**Comment by bzz** [comment]
#53 is merged now, feel free to rebase

**Review by carlosms — CHANGES_REQUESTED** [review]
It looks great!

I don't know if it's because maybe there is some work @ricardobaeta did after you created this branch, but the header is different to master.
In this screenshot master is on top, this branch on the bottom:
screenshot from 2018-02-08 16-21-10

The differences are:
- Different left&right margins
- Missing breadcrumb items
- Wrong style for the dashboard link (it's not uppercase, and the hover color is not right)

Plus the breadcrumb links should probably have a different style on hover. Right now it's the only link with an underline on hover, and no color change. Maybe @ricardobaeta has a proposal for this.

**Comment by smacker** [comment]
1. Margins come from bootstrap grid now. We can change them if we need. (it means we need to change grid)
2. The component itself is correct. The second part of breadcrumbs comes from a description. And it's empty. If there is anything like "asd" it will look the same. You can see it in https://github.com/src-d/code-annotation/issues/57 where I mocked all the data
3. This one is a mistake! Thanks for pointing to it!!! I'm fixing.

**Comment by smacker** [comment]
links are fixed. All of them have the same hover style & uppercase.

**Comment by ricardobaeta** [comment]
> Margins come from bootstrap grid now. We can change them if we need. (it means we need to change grid)

@smacker Let's start to tighten up our design. Please be so kind to address the margins issue.

**Review by carlosms — APPROVED** [review]
:+1:

**Comment by ricardobaeta** [comment]
@smacker As per our conversation, it's all good with the margins. Thank you.

**Review by bzz — APPROVED** [review]
LGTM, thank you for clarifications!

**Pull request merged**
