### PR TITLE
UI update

### LINKED ISSUE #19: Design polishing
The part about annotation is done by product team. We need to:

1. Align frontend with latest wireframes
2. Refactor FE to use CSS Grid layout
3. Deploy branch on staging for @ricardobaeta 
4. Collect feedback from @ricardobaeta (as css/less)
5. Apply feedback

### PR DESCRIPTION
**Pull request by smacker**
Partly fixes https://github.com/src-d/code-annotation/issues/19

Grid thing will be done in a separate PR.

### CODE REVIEW

**Comment by bzz** [comment]
👍 In case of UI changes, in order to speed up the review it might help to add screenshot as well.

**Comment by smacker** [comment]
there are not only visible parts has been changed. But for example confirmation popup was removed. We should use staging for it. But we don't have it right now.

**Review by carlosms — APPROVED** [review]
Works in my machine

**Review by bzz — APPROVED** [review]
LGTM.

Thank you for double-checking, @carlosms !

**Pull request merged**
