### PR TITLE
Add export button to top navbar

### PR DESCRIPTION
**Pull request by smacker**
screen shot 2018-02-28 at 12 57 55

### CODE REVIEW

**Comment by ricardobaeta** [comment]
@smacker Looks solid. I would just remove border-radius & shadow from the element, but it's not mandatory for now.

**Review by bzz — APPROVED** [review]
LGTM

and 👍 for nice refactoring.

**Review by dpordomingo — APPROVED** [review]
LGTM
many thanks for this new shortcut !!
If it's easy for you to do it, please address @ricardobaeta suggestion, and if it's not let's merge now and add his suggestion to our UI todo list
(it would be nice to have a list of UI things to improve; I'm not sure if we already have it)

**Comment by smacker** [comment]
This PR adding one more item in menu. It doesn't change UI. Issue for ui: https://github.com/src-d/code-annotation/issues/179

**Pull request merged**
