### PR TITLE
Reviewer UI (first version)

### PR DESCRIPTION
**Pull request by smacker**
Part of https://github.com/src-d/code-annotation/issues/47

Based on https://github.com/src-d/code-annotation/pull/45

It's a little different from wireframes:
1. There are no breadcrumbs
2. Tables aren't scrollable, but tab content is. It's huge pain to make TBODY scrollable (actually you can't without overriding table layout by css) And then they are inside another flexible div. It's nightmare. I spent half of the day and almost implemented it. But it has too many hacks and I found few cases when it works wrong. We definitely need separate task for it or maybe @ricardobaeta can come up with another solution
3. Better select control is implemented in @ricardobaeta PR, we will replace it later

P.S. There is some magic of mixing grid with flexbox because I had no choice.

screen shot 2018-02-02 at 14 39 28

### CODE REVIEW

**Comment by bzz** [comment]
@smacker great! 

For changes that touch UI part, I find that also having a screenshot attached to PR helps to speed up the review process.

**Comment by smacker** [comment]
@bzz screenshot added

**Review by bzz — APPROVED** [review]
Looks great to me.

I guess there will be subsequent tasks on using a mock data in components to show features, and then replacing it with real data from endpoint in #44

**Comment by carlosms** [comment]
Looks like a very good first version

I've seen just one issue, the contents appear to go past the width no matter my window size:
127 0 0 1_8080_review

And a couple of comments:
- I'd prefer to see the mock data somehow separated, and the table code close to final
- If we merge this as a first version, let's add a comment to https://github.com/src-d/code-annotation/issues/47 saying that breadcrumbs and scrollable table are missing

**Review by carlosms — APPROVED** [review]

**Comment by smacker** [comment]
Thanks, @carlosms I didn't have the bug with the width of the table. Will try to reproduce.

I want to rebase this PR using new components, so @ricardobaeta will be able to start doing visual design on this page without reimplementing the work he did already for annotation page.

**Comment by smacker** [comment]
Rebased on #65 to unlock Ricardo.
It looks like this now:

screen shot 2018-02-08 at 12 58 09

Problem with table width is fixed.

**Pull request merged**
