### PR TITLE
Implement oauth2 state correctly

### PR DESCRIPTION
**Pull request by smacker**
Fixes https://github.com/src-d/code-annotation/issues/21

### CODE REVIEW

**Review by carlosms — APPROVED** [review]

**Comment by carlosms** [comment]
Did you mean fixes #21?

**Comment by smacker** [comment]
yes, sorry. Too many tabs 😅  Changed description

**Review by bzz — APPROVED** [review]
Should we rebase to make CI happy?

LGTM, as soon as CI is green :)

**Comment by smacker** [comment]
all PRs needs to be rebased. I'm merging after CI has passed.

**Pull request merged**
